### ISSUE TITLE
Create initial animal list

### ISSUE THREAD

**Issue by NULL0404** [NULL0404/APCSA-LostAnimal2#7]

**Comment by NULL0404** [comment]
Please make these use the cat and dog subclasses and concentrate them into just cats and dogs

**Comment by TangerineTheGreat115** [comment]
we have had 20 animals added

**Comment by TangerineTheGreat115** [comment]
we have already had 20 animals added

**Comment by NULL0404** [comment]
We need to convert this to implement the subclasses, see #8

**Comment by NULL0404** [comment]
This is close but it needs the time in shelter

**Comment by NULL0404** [comment]
Completed in 9c918d85ccf38b2e92a5d19891d3ef6e25ab5154
